---
version: 2

multi-ecosystem-groups:
  ci-dependencies:
    schedule:
      interval: monthly
    commit-message:
      prefix: dependabot
    labels:
      - dependabot

updates:
  - package-ecosystem: github-actions
    directory: /
    patterns:
      - "*"
    cooldown:
      default-days: 7
    multi-ecosystem-group: ci-dependencies
  - package-ecosystem: pre-commit
    directory: /
    patterns:
      - "*"
    cooldown:
      default-days: 7
    multi-ecosystem-group: ci-dependencies
