---
version: 2

multi-ecosystem-groups:
  ci-dependencies:
    schedule:
      interval: monthly
      timezone: Europe/London
    commit-message:
      prefix: dependabot
    labels:
      - dependabot

updates:
  - package-ecosystem: github-actions
    cooldown:
      default-days: 7
    directory: /
    multi-ecosystem-group: ci-dependencies
    patterns:
      - "*"
  - package-ecosystem: pre-commit
    cooldown:
      default-days: 7
    directory: /
    multi-ecosystem-group: ci-dependencies
    patterns:
      - "*"
