---
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"
  jobs:
    post_checkout:
      - git fetch --tags

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

sphinx:
  configuration: docs/conf.py
