---
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.14"
  jobs:
    pre_install:
      - python -m pip install --upgrade pip
    install:
      - python -m pip install -e . --group docs

sphinx:
  configuration: docs/conf.py
