[default]
extend-ignore-re = [
    # Custom ignore regex patterns:
    # https://github.com/crate-ci/typos/blob/master/docs/reference.md#example-configurations
    ".*(?:#|--|//|/*).*(?:typos):\\s?ignore[^\\n]*\\n",
    ".*(?:typos):\\s?ignore-next-line[^\\n]*\\n[^\\n]*",
]

[files]
extend-exclude = [
    "bibliography.rst",
]

[type.jupyter.extend-words]
arange = "arange"

[type.py.extend-words]
gam = "gam"
lamda = "lamda"
mis = "mis"
nd = "nd"
wht = "wht"
