---
name: Anything Else
description:
  Create a blank issue for anything that does not fit into the other categories
body:
  - id: anything_else
    type: textarea
    attributes:
      label: Add your issue here
    validations:
      required: true
