---
name: Run examples
runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        cache-dependency-path: pyproject.toml
        cache: pip
        python-version: 3.x

    - name: Cache nox
      uses: actions/cache@v4
      with:
        key:
          examples-${{ hashFiles('pyproject.toml') }}-${{
          hashFiles('noxfile.py') }}-${{ env.pythonLocation }}
        path: .nox

    - name: Install nox
      run: python -m pip install nox

    - name: Run examples
      run: nox -s examples
      timeout-minutes: 20
      env:
        FORCE_COLOR: 1

    - name: Generate HTML
      run: nox -s examples -- html
      env:
        FORCE_COLOR: 1

    - name: Upload artefact
      uses: actions/upload-artifact@v4
      with:
        name: Examples
        path: examples/**/*.html
