---
name: Documentation

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize

concurrency:
  cancel-in-progress: true
  group: >-
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  docs:
    if: github.event.pull_request.draft == false
    name: Docs
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v6 # zizmor: ignore[unpinned-uses]
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up uv
        uses: astral-sh/setup-uv@v7 # zizmor: ignore[unpinned-uses]
        with:
          python-version: 3.14

      - name: Install dependencies
        run: |-
          sudo apt-get update
          sudo apt-get install -y pandoc python3-docutils
          uv sync --only-dev

      - name: Build docs
        run: uv run nox -s docs --verbose
        env:
          FORCE_COLOR: 1

      - name: Spellcheck
        uses: crate-ci/typos@v1 # zizmor: ignore[unpinned-uses]

      - name: Run Vale
        uses: errata-ai/vale-action@v2 # zizmor: ignore[unpinned-uses]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          fail_on_error: true
          filter_mode: nofilter
          reporter: github-pr-review
          vale_flags: --glob='!.nox/*'
