---
name: Documentation

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize

concurrency:
  cancel-in-progress: true
  group: >-
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  docs:
    if: github.event.pull_request.draft == false
    name: Docs
    permissions:
      contents: read
    runs-on: ubuntu-slim
    steps:
      - name: Checkout source
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up uv
        # yamllint disable-line rule:line-length
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          python-version: 3.14

      - name: Install dependencies
        run: |-
          sudo apt-get update
          sudo apt-get install -y pandoc python3-docutils
          uv sync --only-dev

      - name: Build docs
        run: uv run nox -s docs --verbose
        env:
          FORCE_COLOR: 1

      - name: Spellcheck
        uses: crate-ci/typos@8a48f81b6c64dcfea44b3633223084c4be58ac5f # v1

      - name: Run Vale
        # yamllint disable-line rule:line-length
        uses: errata-ai/vale-action@518a9136acc6e6668ce7c00d367051e0941e87ff # v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          fail_on_error: true
          filter_mode: nofilter
          reporter: github-pr-review
          vale_flags: --glob='!{.nox,.venv}/**'
          version: 3.14.1
