---
name: Test examples

on:
  push:
    paths:
      - glass/**
    branches:
      - main
  pull_request:
    paths:
      - glass/**
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize

concurrency:
  cancel-in-progress: true
  group: >-
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  test-examples:
    if: github.event.pull_request.draft == false
    name: Test examples
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache tox
        uses: actions/cache@v4
        with:
          key: test-${{ hashFiles('pyproject.toml') }}
          path: .tox

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache-dependency-path: pyproject.toml
          cache: pip
          python-version: 3.x

      - name: Install tox
        run: python -m pip install tox

      - name: Run examples
        run: tox -s examples
        env:
          FORCE_COLOR: 1

      - name: Generate HTML
        run: tox -s examples -- html
        env:
          FORCE_COLOR: 1

      - name: Upload artefact
        uses: actions/upload-artifact@v4
        with:
          name: Examples
          path: examples/**/*.html
