---
name: Linting

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize

concurrency:
  cancel-in-progress: true
  group: >-
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  prek:
    if: github.event.pull_request.draft == false
    name: Run linting
    permissions:
      contents: read
    runs-on: ubuntu-slim
    steps:
      - name: Checkout source
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up uv
        # yamllint disable-line rule:line-length
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          python-version: 3.14

      - name: Install only dev dependencies
        run: uv sync --only-dev

      - name: Run prek
        run: uv run nox -s lint
        env:
          FORCE_COLOR: 1
