---
name: Linting

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize

concurrency:
  cancel-in-progress: true
  group: >-
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  prek:
    if: github.event.pull_request.draft == false
    name: Run linting
    permissions:
      contents: read
    runs-on: ubuntu-slim
    steps:
      - name: Checkout source
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up uv
        # yamllint disable-line rule:line-length
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          python-version: 3.14

      - name: Install only dev dependencies
        run: uv sync --only-dev

      - name: Run prek
        run: uv run nox -s lint
        env:
          FORCE_COLOR: 1
