---
name: PR Title Checker

on:
  pull_request_target: # zizmor: ignore[dangerous-triggers]
    types:
      - edited
      - labeled
      - opened
      - synchronize
      - unlabeled

jobs:
  check-pr-title:
    if: >-
      github.event.pull_request.user.login != 'allcontributors[bot]' &&
      github.event.pull_request.user.login != 'dependabot[bot]'
    permissions: {}
    runs-on: ubuntu-latest
    steps:
      - name: Enforce PR title format
        # yamllint disable-line rule:line-length
        uses: thehanimo/pr-title-checker@7fbfe05602bdd86f926d3fb3bccb6f3aed43bc70 # v1.4.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pass_on_octokit_error: false
