---
name: Release

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  dist:
    runs-on: ubuntu-slim
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout source
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up uv
        if: github.event_name == 'workflow_dispatch'
        # yamllint disable-line rule:line-length
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          enable-cache: false
          python-version: 3.14

      - name: Set build version for TestPyPI
        if: github.event_name == 'workflow_dispatch'
        run: |-
          uv sync --only-dev
          VERSION=$(uv run hatchling version | cut -d+ -f1)
          echo "SETUPTOOLS_SCM_PRETEND_VERSION=$VERSION" >> "$GITHUB_ENV"

      # yamllint disable-line rule:line-length
      - uses: hynek/build-and-inspect-python-package@2abe76da66d0a6a4a227101f9348ee855797cfa5 # v3.0.1

  publish-pypi:
    if: github.event_name == 'release' && github.event.action == 'published'
    needs: dist
    runs-on: ubuntu-latest
    environment:
      name: publish
      url: https://pypi.org/project/glass
    permissions:
      id-token: write
    steps:
      - name: Download distributions
        # yamllint disable-line rule:line-length
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: Packages
          path: dist

      - name: List distributions to be deployed
        run: ls -l dist/

      - name: Publish to PyPI
        # yamllint disable-line rule:line-length
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2
        with:
          verbose: true

  publish-test-pypi:
    if: github.event_name == 'workflow_dispatch'
    needs: dist
    runs-on: ubuntu-latest
    environment:
      name: test-publish
      url: https://test.pypi.org/project/glass
    permissions:
      id-token: write
    steps:
      - name: Download distributions
        # yamllint disable-line rule:line-length
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: Packages
          path: dist

      - name: List distributions to be deployed
        run: ls -l dist/

      - name: Publish to TestPyPI
        # yamllint disable-line rule:line-length
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
          verbose: true
