---
name: Release

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  dist:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout source
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up uv
        if: github.event_name == 'workflow_dispatch'
        # yamllint disable-line rule:line-length
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          enable-cache: false
          python-version: 3.14

      - name: Set build version for TestPyPI
        if: github.event_name == 'workflow_dispatch'
        run: |-
          uv sync --only-dev
          VERSION=$(uv run hatchling version | cut -d+ -f1)
          echo "SETUPTOOLS_SCM_PRETEND_VERSION=$VERSION" >> "$GITHUB_ENV"

      # yamllint disable-line rule:line-length
      - uses: hynek/build-and-inspect-python-package@d44ca7d91762de7a7d5436ddae667c6da6d1c3df # v2

  publish-pypi:
    if: github.event_name == 'release' && github.event.action == 'published'
    needs: dist
    runs-on: ubuntu-latest
    environment:
      name: publish
      url: https://pypi.org/project/glass
    permissions:
      id-token: write
    steps:
      - name: Download distributions
        # yamllint disable-line rule:line-length
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: Packages
          path: dist

      - name: List distributions to be deployed
        run: ls -l dist/

      - name: Publish to PyPI
        # yamllint disable-line rule:line-length
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
        with:
          verbose: true

  publish-test-pypi:
    if: github.event_name == 'workflow_dispatch'
    needs: dist
    runs-on: ubuntu-latest
    environment:
      name: test-publish
      url: https://test.pypi.org/project/glass
    permissions:
      id-token: write
    steps:
      - name: Download distributions
        # yamllint disable-line rule:line-length
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: Packages
          path: dist

      - name: List distributions to be deployed
        run: ls -l dist/

      - name: Publish to TestPyPI
        # yamllint disable-line rule:line-length
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
          verbose: true
