---
name: Run examples (reusable workflow)

on:
  workflow_call:

concurrency:
  cancel-in-progress: true
  group: >-
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  run-examples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up uv
        # yamllint disable-line rule:line-length
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          python-version: 3.14

      - name: Cache nox
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v5
        with:
          key:
            examples-${{ hashFiles('pyproject.toml') }}-${{
            hashFiles('noxfile.py') }}
          path: .nox

      - name: Install only dev dependencies
        run: uv sync --only-dev

      - name: Run examples
        run: uv run nox -s examples
        timeout-minutes: 25
        env:
          FORCE_COLOR: 1

      - name: Generate HTML
        run: uv run nox -s examples -- html
        env:
          FORCE_COLOR: 1

      - name: Upload artefact
        # yamllint disable-line rule:line-length
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: Examples
          path: examples/**/*.html
