---
name: Run examples (reusable workflow)

on:
  workflow_call:

concurrency:
  cancel-in-progress: true
  group: >-
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  run-examples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          cache-dependency-path: pyproject.toml
          cache: pip
          python-version: 3.x

      - name: Cache nox
        uses: actions/cache@v4
        with:
          key:
            examples-${{ hashFiles('pyproject.toml') }}-${{
            hashFiles('noxfile.py') }}-${{ env.pythonLocation }}
          path: .nox

      - name: Install nox
        run: python -m pip install nox[uv]

      - name: Run examples
        run: nox -s examples
        timeout-minutes: 20
        env:
          FORCE_COLOR: 1

      - name: Generate HTML
        run: nox -s examples -- html
        env:
          FORCE_COLOR: 1

      - name: Upload artefact
        uses: actions/upload-artifact@v5
        with:
          name: Examples
          path: examples/**/*.html
