---
name: Test examples

on:
  pull_request:

jobs:
  test-examples-on-label:
    if: contains(github.event.pull_request.labels.*.name, 'run-examples')
    name: On label
    uses: glass-dev/glass/.github/workflows/run-examples.yml@main
