---
name: Test examples on label

on:
  pull_request:

concurrency:
  cancel-in-progress: true
  group: >-
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  test-examples-on-label:
    if: contains(github.event.pull_request.labels.*.name, 'run-examples')
    name: Test examples on label
    uses: glass-dev/glass/.github/workflows/run-examples.yml@saransh/run-examples-on-label
