name: tox
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  tox:
    strategy:
      matrix:
        toxenv:
        - flake8
        - test
        - docs
    name: ${{ matrix.toxenv }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Install Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install tox
      run: |
        pip install tox
    - name: Run ${{ matrix.toxenv }}
      run: |
        tox -e ${{ matrix.toxenv }}
